M_CATMecModLiveUseItf=mkSharedLibrary "D:\DS\B421\.\CATMecModLiveUseItf\CATMecModLiveUseItf.m" CATMecModLiveUseItf - - - - - -
TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0FM M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATDialogEngine M_CATMathematics M_DI0PANV2 M_CATAfrFoundation M_CATAfrItf M_CATVisItf M_CATAfrCompanion M_CATAfrComponentsModel M_CATMecModUseItf M_CATMecModLiveUseItf M_CATOmx M_CATPLMIdentificationAccess M_CATPLMComponentInterfaces M_KnowledgeItf M_CATGSMUseItf M_DataCommonProtocolUse M_ObjectModelerSystem M_CATStrUseItf M_SDQtTreeTable
M_V6AddinCmdTest=mkSharedLibrary "D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m" V6AddinCmdTest - - - - - -
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
GProtected=D:\MyJob\NewProductV6\.\NewV6WorkFrm\ProtectedGenerated\win_b64
IProtected=D:\MyJob\NewProductV6\.\NewV6WorkFrm\ProtectedInterfaces
M_CATVisItf=mkSharedLibrary "D:\DS\B421\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "D:\DS\B421\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CATDialogEngine=mkSharedLibrary "D:\DS\B421\.\DialogEngine\CATDialogEngine.m" CATDialogEngine - - - - - -
GLocal=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\LocalGenerated\win_b64
ILocal=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "D:\DS\B421\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=D:\MyJob\NewProductV6\.\NewV6WorkFrm\PublicInterfaces
GPublic=D:\MyJob\NewProductV6\.\NewV6WorkFrm\PublicGenerated\win_b64
M_CATOmx=mkSharedLibrary "D:\DS\B421\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m
MOD_INCPATH="D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\src" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\LocalInterfaces" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "D:\DS\B421\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
M_CATMathematics=mkSharedLibrary "D:\DS\B421\.\Mathematics\CATMathematics.m" CATMathematics - - - - - -
GPrivate=D:\MyJob\NewProductV6\.\NewV6WorkFrm\PrivateGenerated\win_b64
IPrivate=D:\MyJob\NewProductV6\.\NewV6WorkFrm\PrivateInterfaces
USE_PDB_FILE=YES
M_SDQtTreeTable=mkSharedLibrary "D:\MyJob\NewProductV6\.\NewV6WorkFrm\SDQtTreeTable.m" SDQtTreeTable - - - - - -
WSPATH=D:\MyJob\NewProductV6\.
M_CATMecModUseItf=mkSharedLibrary "D:\DS\B421\.\CATMecModUseItf\CATMecModUseItf.m" CATMecModUseItf - - - - - -
MODPATH=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m
FWNAME=NewV6WorkFrm
WSROOT=D:\MyJob\NewProductV6\.
CONTNAME=V6AddinCmdTest
WSSOURCES=D:\MyJob\NewProductV6\.
M_CATAfrComponentsModel=mkSharedLibrary "D:\DS\B421\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
WSENAME_msg=NewV6WorkFrm\V6AddinCmdTest.m
MODDIRNAME=V6AddinCmdTest.m
M_CATAfrCompanion=mkSharedLibrary "D:\DS\B421\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "D:\DS\B421\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "D:\DS\B421\.\System\JS0GROUP.m" JS0GROUP - - - - - -
NAME=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\Objects\win_b64\.mkdata.mkb
M_CATAfrItf=mkSharedLibrary "D:\DS\B421\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_V6AddinCmdTest
TARGET_DYNLINK=link1st link2nd
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0FM JS0GROUP CATDialogEngine CATMathematics DI0PANV2 CATAfrFoundation CATVisItf CATMecModUseItf CATMecModLiveUseItf CATPLMComponentInterfaces CATLifSpecs CATGSMUseItf DataCommonProtocolUse ObjectModelerSystem KnowledgeItf CATStrUseItfCPP SDQtTreeTable
WSSOURCES_Concat="D:\MyJob\NewProductV6\." "D:\DS\B421\." "D:\MyJob\B421\B421\."
M_DI0PANV2=mkSharedLibrary "D:\DS\B421\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AfrFoundation,21ED1151;BSFBuildtimeData,21DD1140;BatchInfrastructure,21ED1151;CAT3DPhysicalRepInterfaces,21EE1151;CATAnnotationUseItf,21EE1151;CATDibModelerUseItf,21EE1151;CATGSMUseItf,21EE1151;CATMecModLiveUseItf,21EE1151;CATMecModUIUseItf,21EE1151;CATMecModUseItf,21EE1151;CATPLMComponentInterfaces,21EE1151;CATPLMIdentificationAccess,21EC1151;CATPLMIntegrationAccess,21ED1151;CATPLMIntegrationUse,21EE1151;CATPLMUpdateUseItf,21EE1151;CATPartUseItf,21EE1151;CATStrUseItf,21EE1151;DataCommonProtocolUse,21ED1151;Dialog,21ED1151;DialogEngine,21EE1151;GMModelInterfaces,21EE1151;KnowledgeInterfaces,21EC1151;Mathematics,21ED1151;ObjectModelerBase,21ED1151;ObjectModelerSystem,21ED1151;PLMBatchDataAccessInterfaces,21EE1151;PLMDictionaryNavServices,21EE1151;ProductStructureInterfaces,21EE1151;ProductStructureUseItf,21EE1151;SpecialAPI,21ED1151;System,21ED1151;SystemTS,21EC1151;VisualizationInterfaces,21ED1151;XMLParserItf,21ED1151;AdvancedMathematics,20DD1151;AfrComponentsModel,20CC1141;AfrInterfaces,20DD1131;CATMathStream,20DD1151;CATPLMIntegrationAccessItf,20DD1151;CATStyleProcessor,20DD1141;CATVirtualVaultSystem,20DD1151;Communications,20DD1151;GeometricObjects,20DD1151;IVInterfaces,20DD1151;InteractiveInterfaces,20DD1151;IntrospectionInfrastructure,20CC1141;MultimediaPixelImage,20DD1151;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMModelerBaseInterfaces,20DD1151;SGInfra,20CC1151;SGManager,20CC1151;UIVCoreTools,20DD1151;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;
FWCOMPANYNAME=
BUILD=YES
MOD_Container=V6AddinCmdTest.m
LOCAL_LDFLAGS="D:/MyJob/SDQtTreeTable.lib" /LIBPATH:"D:\MyJob\qtlib" Qt5Core.lib Qt5Gui.lib Qt5Widgets.lib user32.lib
WS_Concat="D:\MyJob\NewProductV6\." "D:\DS\B421\." "D:\MyJob\B421\B421\."
FWmkHLpath=D:\MyJob\NewProductV6\.\NewV6WorkFrm\IdentityCard\Objects\win_b64\.mkHLpath.mk
MOD_ObjectsPath=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\Objects\win_b64
M_ObjectModelerSystem=mkSharedLibrary "D:\DS\B421\.\ObjectModelerSystem\ObjectModelerSystem.m" ObjectModelerSystem - - - - - -
RTViewDataListPath=D:\MyJob\NewProductV6\.\NewV6WorkFrm\various\win_b64\V6AddinCmdTest.m\module.data
M_JS0FM=mkSharedLibrary "D:\DS\B421\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "D:\DS\B421\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkSharedLibrary
M_CATStrUseItf=mkSharedLibrary "D:\DS\B421\.\CATStrUseItf\CATStrUseItf.m" CATStrUseItf - - - - - -
BUILT_OBJECT_TYPE=SHARED LIBRARY
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="D:\MyJob\NewProductV6\.\NewV6WorkFrm\PrivateInterfaces" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\PrivateGenerated\win_b64" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\ProtectedInterfaces" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\ProtectedGenerated\win_b64" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\PublicInterfaces" "D:\MyJob\NewProductV6\.\NewV6WorkFrm\PublicGenerated\win_b64"
MOD_SrcPath=D:\MyJob\NewProductV6\.\NewV6WorkFrm\V6AddinCmdTest.m\src
DOC_RTViewDataListPath=D:\MyJob\NewProductV6\.\NewV6WorkFrm\various\win_b64.doc\V6AddinCmdTest.m\module.data
LINK_WITH=JS0FM JS0GROUP CATDialogEngine CATMathematics DI0PANV2 CATAfrFoundation CATVisItf CATMecModUseItf CATMecModLiveUseItf CATPLMComponentInterfaces CATLifSpecs CATGSMUseItf DataCommonProtocolUse ObjectModelerSystem KnowledgeItf CATStrUseItfCPP SDQtTreeTable
MOD_Included=M_V6AddinCmdTest
M_CATPLMIdentificationAccess=mkSharedLibrary "D:\DS\B421\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "D:\DS\B421\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=D:\MyJob\NewProductV6\.\NewV6WorkFrm
MK_BUILD_CONFIGURATION=
MKMK_DEBUG=YES
M_CATGSMUseItf=mkSharedLibrary "D:\DS\B421\.\CATGSMUseItf\CATGSMUseItf.m" CATGSMUseItf - - - - - -
FWSOURCES=D:\MyJob\NewProductV6\.\NewV6WorkFrm
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "D:\DS\B421\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
F_NewV6WorkFrm=mkFrameworkCode "D:\MyJob\NewProductV6\.\NewV6WorkFrm" NewV6WorkFrm - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=NewV6WorkFrm
M_DataCommonProtocolUse=mkSharedLibrary "D:\DS\B421\.\DataCommonProtocolUse\DataCommonProtocolUse.m" DataCommonProtocolUse - - - - - -
MODNAME=V6AddinCmdTest
REAL_LINK_WITH=JS0FM JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATDialogEngine CATMathematics DI0PANV2 CATAfrFoundation CATAfrItf CATVisItf CATAfrCompanion CATAfrComponentsModel CATMecModUseItf CATMecModLiveUseItf CATOmx CATPLMIdentificationAccess CATPLMComponentInterfaces KnowledgeItf CATGSMUseItf DataCommonProtocolUse ObjectModelerSystem CATStrUseItf SDQtTreeTable
