// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module SDQtTreeTable
#======================================================================
#  2026/08/07 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM \
JS0GROUP \ 
CATDialogEngine \
DI0PANV2

LOCAL_LDFLAGS = \
  "D:/MyJob/NewProductV6/NewV6WorkFrm/SDQtTreeTable.m/Objects/win_b64/SDQtTreeTable.lib" \
  /LIBPATH:"C:\Qt\Qt5.9.0\5.9\msvc2015_64\lib" \
  Qt5Core.lib Qt5Gui.lib Qt5Widgets.lib user32.lib
# END WIZARD EDITION ZONE
