//===================================================================
// COPYRIGHT sd 2026/07/30
//===================================================================
// V6AddinCmdTest.cpp
// Header definition of class V6AddinCmdTest
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2026/07/30 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByV6AddinCmdTest_H
#define ExportedByV6AddinCmdTest_H
#if defined(__V6AddinCmdTest)
# define ExportedByV6AddinCmdTest   DSYExport
#else // __V6AddinCmdTest
# define ExportedByV6AddinCmdTest   DSYImport
#endif  // __V6AddinCmdTest
#include "DSYExport.h"
#endif //ExportedByV6AddinCmdTest_H

