//===================================================================
// COPYRIGHT sd 2026/07/30
//===================================================================
// TestCmd.h
// Header definition of class TestCmd
//===================================================================
//
// Usage notes:
//   TestCmd 是树表封装的示例命令。
//   重构说明(2026/08/07):
//   原 V6AddinCmdTest 内嵌的树表已迁移到 SDQtTreeTable 模块,
//   这里改为通过 CAAQtTreeTableHost 宿主类使用,
//   与 CAA 工程 SDRdProcessPreparationCmd 使用 CAAQtTableHost 的方式一致。
//
//===================================================================
//  2026/07/30 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TestCmd_H
#define TestCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "TestDlg.h"
#include "CATApplicationFrame.h"
#include "CAAQtTreeTableHost.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* 树表示例命令。
* <p>
* 演示两个数据来源:
* <br> a) 读取文件:对话框首次挂载树表时调用 LoadDefaultData()
*         加载 SDQtTreeTable.m 根目录的 TreeTableData.json;
* <br> b) 响应事件:视图点击事件(ActionOne)中构造 QtTreeNode 调用
*         SetData() 填充树表。
*/
class TestCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( TestCmd, CATStateCommand )

public:

TestCmd();
virtual ~TestCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
* 视图点击事件:演示"响应事件后 SetData 填表"。
*/
virtual CATBoolean  ActionOne(void * data);

/**
* 对话框尺寸变化通知:负责挂载/缩放 Qt 树表。
*/
virtual void OnDialogSizeChanged();

private:

/**
* 确保树表已挂载到对话框 Frame(未挂载则 Attach + 配置 + 加载默认数据),
* 随后按当前尺寸 Resize。Frame HWND 未就绪时等下一次尺寸通知重试。
*/
void EnsureTreeTableAttached();

/**
* 树表挂载成功后的配置:注册行点击回调、设置样式、加载默认 JSON 数据。
*/
void ConfigureTreeTable();

/**
* 树表行点击回调(静态,通过 context 取回命令对象)。
*/
static void OnTreeRowClicked(
	void *context,
	int row,
	int column,
	const char *columnId,
	const char *cellText);

CATIndicationAgent	* _Indication;
TestDlg* _test;
CAAQtTreeTableHost _treeTableHost;
};

//----------------------------------------------------------------------

#endif
