//===================================================================
// COPYRIGHT sd 2026/08/07
//===================================================================
// SDQtTreeTable.cpp
// Header definition of class SDQtTreeTable
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2026/08/07 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedBySDQtTreeTable_H
#define ExportedBySDQtTreeTable_H
#if defined(__SDQtTreeTable)
# define ExportedBySDQtTreeTable   DSYExport
#else // __SDQtTreeTable
# define ExportedBySDQtTreeTable   DSYImport
#endif  // __SDQtTreeTable
#include "DSYExport.h"
#endif //ExportedBySDQtTreeTable_H

