// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module V6AddinCmdTest
#======================================================================
#  2026/07/30 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM  \
JS0GROUP  \
CATDialogEngine \
CATMathematics \
DI0PANV2 \ 
CATAfrFoundation \
CATVisItf \
CATMecModUseItf \
CATMecModLiveUseItf \
CATPLMComponentInterfaces \
CATLifSpecs \
CATGSMUseItf \
DataCommonProtocolUse \
ObjectModelerSystem \
KnowledgeItf \
CATStrUseItfCPP \
SDQtTreeTable

LOCAL_LDFLAGS = \
	"D:/MyJob/SDQtTreeTable.lib"	 \
    /LIBPATH:"D:\MyJob\qtlib" \
    Qt5Core.lib Qt5Gui.lib Qt5Widgets.lib user32.lib 
# END WIZARD EDITION ZONE
