//===================================================================
// COPYRIGHT sd 2026/07/30
//===================================================================
// TestCmd.cpp
// Header definition of class TestCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2026/07/30 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TestCmd_H
#define TestCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "TestDlg.h"
#include "CATApplicationFrame.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class TestCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( TestCmd, CATStateCommand )

public:

TestCmd();
virtual ~TestCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);
//virtual void ShowBtn();
virtual void OnDialogSizeChanged();


private:

CATIndicationAgent	* _Indication;
TestDlg* _test;
};

//----------------------------------------------------------------------

#endif
