//===================================================================
// COPYRIGHT sd 2026/07/30
//===================================================================
// TestCmd.cpp
// Implementation of class TestCmd
//===================================================================
//
// Usage notes:
//   树表封装示例:通过 CAAQtTreeTableHost 宿主类把 Qt 树表嵌入 CAA 对话框。
//   数据来源:
//     a) 读取文件 —— ConfigureTreeTable() 调用 LoadDefaultData(),
//        加载 SDQtTreeTable.m 根目录 TreeTableData.json;
//     b) 响应事件 —— ActionOne() 中构造 QtTreeNode 调用 SetData()。
//
//===================================================================
//  2026/07/30 Creation: Code generated by the 3DS wizard
//  2026/08/07 Refactor: 树表改用 SDQtTreeTable 模块封装类
//===================================================================

#include "TestCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
#include "CATDlgFrame.h"

#include <iostream>
#include <cstring>

CATCreateClass( TestCmd);

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TestCmd::TestCmd() :
CATStateCommand ("TestCmd", CATDlgEngOneShot, CATCommandModeShared)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
,_Indication(NULL)
{
	_test = new TestDlg(CATApplicationFrame::GetFrame()->GetMainWindow(), "TestDlg");
	_test->Build();

	// 按显示器（屏幕）分辨率设置对话框默认大小并居中：
	// SetRectDimensions 参数顺序：左上角 X、左上角 Y、高度、宽度（像素）。
	{
		int screenW = GetSystemMetrics(SM_CXSCREEN);
		int screenH = GetSystemMetrics(SM_CYSCREEN);
		int dlgW = screenW * 6 / 10; // 宽度取屏幕的 %
		int dlgH = screenH * 5 / 10; // 高度取屏幕的 %
		if (dlgW < 1200)
			dlgW = 1200; 
		_test->SetRectDimensions(
			(screenW - dlgW) / 2,
			(screenH - dlgH) / 2,
			dlgH,
			dlgW);
	}
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TestCmd::~TestCmd()
{
	// 销毁 Qt 树表(内部会自动解除窗口父子关系)。
	_treeTableHost.Destroy();

	if (_test != NULL)
	{
		_test->SetVisibility(CATDlgHide);
		_test->RequestDelayedDestruction();
		_test = NULL;
	}
	if (_Indication != NULL)
		_Indication->RequestDelayedDestruction();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void TestCmd::BuildGraph()
{
	_test->SetVisibility(CATDlgShow);

// TODO: Define the StateChart
// ---------------------------
	_Indication = new CATIndicationAgent ("Indication");
	CATMathPlane PlaneXY;
	_Indication->SetMathPlane (PlaneXY);
	CATDialogState * initialState = GetInitialState("initialState");
	initialState->AddDialogAgent (_Indication);

	AddTransition( initialState, initialState,
		IsOutputSetCondition (_Indication),
		Action ((ActionMethod) &TestCmd::ActionOne));

	// 对话框尺寸变化时挂载/缩放 Qt 树表。
	AddAnalyseNotificationCB(_test, _test->GetWindSizeNotification(),
		(CATCommandMethod)&TestCmd::OnDialogSizeChanged, NULL);
}

//-------------------------------------------------------------------------
// OnDialogSizeChanged()
//-------------------------------------------------------------------------
void TestCmd::OnDialogSizeChanged()
{
	EnsureTreeTableAttached();
}

//-------------------------------------------------------------------------
// EnsureTreeTableAttached()
//-------------------------------------------------------------------------
void TestCmd::EnsureTreeTableAttached()
{
	if (!_treeTableHost.IsAttached())
	{
		CATDlgFrame *host = _test->GetQtTreeTableHost();
		if (!_treeTableHost.Attach(host))
		{
			// 对话框 HWND 尚未创建时直接返回,在下次尺寸通知中再次尝试。
			return;
		}

		ConfigureTreeTable();
	}

	_treeTableHost.Resize();
}

//-------------------------------------------------------------------------
// ConfigureTreeTable()
//-------------------------------------------------------------------------
void TestCmd::ConfigureTreeTable()
{
	// 注册行点击回调。
	_treeTableHost.SetRowClickCallback(&TestCmd::OnTreeRowClicked, this);

	// 样式:行高 27 像素 + 交替行背景色。
	QtTreeStyle style;
	memset(&style, 0, sizeof(style));
	style.rowHeight = 27;
	style.alternatingRowColors = 1;
	_treeTableHost.SetStyle(&style);

	// 打开树表动画:节点展开/折叠时带平滑过渡效果。
	// enable=1 打开,enable=0 关闭;durationMs 为预留的动画时长参数。
	_treeTableHost.SetAnimation(1, 200);

	// 1) 设置表头字段:列定义(id / 表头文本 / JSON字段 / 宽度 / 是否数值排序)。
	static const QtTreeColumn kColumns[] =
	{
		{ "taskName",  "任务名称",   "name",      205, 0 },
		{ "code",      "编号",       "code",      85,  0 },
		{ "owner",     "负责人",     "owner",     95,  0 },
		{ "startDate", "开始日期",   "startDate", 100, 0 },
		{ "endDate",   "结束日期",   "endDate",   100, 0 },
		{ "budget",    "预算(万元)", "budget",    100, 1 },
		{ "actual",    "实际(万元)", "actual",    100, 1 },
		{ "state",     "备注",       "state",     210, 0 }
	};

	// 2) 多级表头单元格(title / 起始行 / 起始列 / 跨行 / 跨列 / 可排序)。
	static const QtTreeHeaderCell kHeaderCells[] =
	{
		{ "项目信息",   0, 0, 1, 3, 0 },
		{ "计划与进度", 0, 3, 1, 3, 0 },
		{ "成本与状态", 0, 5, 1, 2, 0 },
		{ "备注",       0, 7, 3, 1, 0 },
		{ "任务名称",   1, 0, 2, 1, 1 },
		{ "编号",       1, 1, 2, 1, 1 },
		{ "负责人",     1, 2, 2, 1, 1 },
		{ "计划日期",   1, 3, 1, 2, 0 },
		{ "成本",       1, 5, 1, 2, 0 },
		{ "开始日期",   2, 3, 1, 1, 1 },
		{ "结束日期",   2, 4, 1, 1, 1 },
		{ "预算(万元)", 2, 5, 1, 1, 1 },
		{ "实际(万元)", 2, 6, 1, 1, 1 }
	};

	_treeTableHost.SetColumns(
		kColumns,
		sizeof(kColumns) / sizeof(kColumns[0]),
		kHeaderCells,
		sizeof(kHeaderCells) / sizeof(kHeaderCells[0]),
		28);

	// 3) 进度条列:5 为"完成进度"列;-1 关闭进度条(不是每种数据都需要)。
	_treeTableHost.SetProgressColumn(-1);

	// 列宽随窗口宽度按比例缩放:1 开启(默认),0 关闭。
	_treeTableHost.SetColumnAutoScale(1);

	// 4) 设置数据文件并填入:读取哪些字段由列定义里的 field 决定。
	//    数据来源 a) 读取文件;数据来源 b) 见 ActionOne 的 SetData 示例。
	_treeTableHost.SetDataFile(
		"D:/MyJob/NewProductV6/NewV6WorkFrm/SDQtTreeTable.m/TreeTableData.json");
	if (!_treeTableHost.LoadData())
	{
		std::cout << "[SDQtTreeTable] 加载数据文件失败" << std::endl;
	}
}

//-------------------------------------------------------------------------
// OnTreeRowClicked()
//-------------------------------------------------------------------------
void TestCmd::OnTreeRowClicked(
	void *context,
	int row,
	int column,
	const char *columnId,
	const char *cellText)
{
	TestCmd *command = static_cast<TestCmd *>(context);
	if (!command || !columnId || !cellText)
		return;

	std::cout
		<< "树表点击: row=" << row
		<< ", column=" << column
		<< ", id=" << columnId
		<< ", text=" << cellText
		<< std::endl;

	// 示例:根据 columnId 分流业务(与 CAA 工程 OnTableRowClicked 一致)。
	if (strcmp(columnId, "code") == 0)
	{
		// 在这里编写"按编号查询"等业务逻辑。
	}
}

//-------------------------------------------------------------------------
// ActionOne()
//-------------------------------------------------------------------------
CATBoolean TestCmd::ActionOne( void *data )
{
	if (_Indication != NULL)
		_Indication->InitializeAcquisition();

	// 数据来源 b):响应事件后程序化填充树数据。
	// 业务场景:视图点击、PLM 查询、命令回调等事件发生后,
	// 把结果构造成 QtTreeNode 数组调用 SetData() 即可刷新树表。
	static const char *kChildCells[9] =
	{
		"事件响应子任务", "EVT-001-01", "李四",
		"2026-08-07", "2026-08-15", "",
		"4.0", "0.0", "未开始"
	};

	static const char *kRootCells[9] =
	{
		"事件响应示例任务", "EVT-001", "张三",
		"2026-08-07", "2026-08-20", "",
		"10.0", "0.0", "进行中"
	};

	QtTreeNode child;
	memset(&child, 0, sizeof(child));
	child.cells = kChildCells;
	child.cellCount = 9;
	child.progress = 0;
	child.checkable = 1;

	QtTreeNode root;
	memset(&root, 0, sizeof(root));
	root.cells = kRootCells;
	root.cellCount = 9;
	root.progress = 0;
	root.checkable = 1;
	root.expanded = 1;
	root.childCount = 1;
	root.children = &child;

	_treeTableHost.SetData(&root, 1);

	return TRUE;
}
